/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectroboliga2014;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Tilen
 */
public class ForegroundPane extends javax.swing.JPanel {

    /**
     * Creates new form ForegroundPane
     */
    
    private String coordinatesToDraw = "";
    private boolean check = false;        
    
    public ForegroundPane() {
        initComponents();
        
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        setOpaque(false);
        Graphics2D g2 = (Graphics2D) g;

        if (check == true) {
            int firstX = 0;
            int firstY = 0;
            int secondX = 0;
            int secondY = 0;

            String delim = "-";
            String[] tokens = coordinatesToDraw.split(delim);
            int maxLen = tokens.length;
            int x = Integer.parseInt(tokens[0]);
            int y = Integer.parseInt(tokens[1]);
            firstX = x;
            firstY = y;
            for (int i = 2; i < maxLen; i++) {
                if (i%2 == 0) {
                    secondX = Integer.parseInt(tokens[i]);
                } else if (i%2 == 1) {
                    secondY = Integer.parseInt(tokens[i]);
                    g2.setColor(Color.RED);
                    g2.setStroke(new BasicStroke(2));
                    g2.drawLine(firstX, firstY, secondX, secondY);
                    g2.setColor(Color.blue);
                    g2.setStroke(new BasicStroke(3));
                    g2.drawLine(firstX, firstY, firstX, firstY);
                    g2.drawLine(secondX, secondY, secondX, secondY);  
                    firstX = secondX;
                    firstY = secondY;
                } else {

                }
            }
            check = false;
        }      
    }

    public void iLovePainting(String coordinates) {
        coordinatesToDraw = coordinates;
        check = true;
        repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
